OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: AISquare
    Domain: aisquare.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: NaverPay
    Domain: naverpay.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
